-- Supabase Data Sync
-- Generated: 2026-06-06T17:39:04.506Z

-- Add tags and featured columns to books
ALTER TABLE books ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE books ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;

INSERT INTO books (id, title, author, cover, description, tags, featured) VALUES
  ('1984', '1984', '乔治·奥威尔', '/books/covers/1984.webp', '反乌托邦文学的巅峰之作，描绘一个极权统治下的恐怖未来世界', ARRAY['classic','novel','dystopia','english'], false),
  ('古典部系列', '古典部系列', '米泽穗信', '/books/covers/古典部系列.webp', '以神山高中古典部为舞台的青春推理小说系列', ARRAY['light-novel','japanese'], true),
  ('魔女之旅', '魔女之旅', '白石定规', '/books/covers/魔女之旅.webp', '讲述魔女伊蕾娜周游各国的故事', ARRAY['light-novel','japanese'], true),
  ('小市民系列', '小市民系列', '米泽穗信', '/books/covers/小市民系列.webp', '以小市民为主题的推理小说系列', ARRAY['light-novel','japanese'], true),
  ('三个火枪手', '三个火枪手', '大仲马', '/books/covers/三个火枪手.webp', '法国浪漫主义作家大仲马的代表作，讲述达达尼昂与三位火枪手的冒险故事', ARRAY['classic','novel','adventure','french'], false),
  ('了不起的盖茨比', '了不起的盖茨比', '菲茨杰拉德', '/books/covers/了不起的盖茨比.webp', '美国作家菲茨杰拉德的代表作，描绘美国梦的幻灭', ARRAY['classic','novel','american'], false),
  ('仲夏夜之梦', '仲夏夜之梦', '莎士比亚', '/books/covers/仲夏夜之梦.webp', '莎士比亚最著名的喜剧之一，讲述雅典城外森林中的奇幻爱情故事', ARRAY['classic','drama','romance','english'], false),
  ('傲慢与偏见', '傲慢与偏见', '简·奥斯汀', '/books/covers/傲慢与偏见.webp', '英国文学史上最受欢迎的小说之一，讲述伊丽莎白与达西的爱情故事', ARRAY['classic','novel','romance','english'], false),
  ('动物农场', '动物农场', '乔治·奥威尔', '/books/covers/动物农场.webp', '一部政治讽刺寓言，以动物革命隐喻极权主义的兴起', ARRAY['classic','novel','dystopia','english'], false),
  ('包法利夫人', '包法利夫人', '福楼拜', '/books/covers/包法利夫人.webp', '法国现实主义文学的里程碑，讲述农家女爱玛的悲剧人生', ARRAY['classic','novel','french'], false),
  ('十日谈', '十日谈', '薄伽丘', '/books/covers/十日谈.webp', '欧洲文学史上第一部现实主义巨著，以十个青年讲故事的形式展开', ARRAY['classic','short-story','italian'], false),
  ('卡拉马佐夫兄弟', '卡拉马佐夫兄弟', '陀思妥耶夫斯基', '/books/covers/卡拉马佐夫兄弟.webp', '陀思妥耶夫斯基的巅峰之作，探讨信仰、理性和自由意志的终极冲突', ARRAY['classic','novel','philosophy','russian'], false),
  ('双城记', '双城记', '查尔斯·狄更斯', '/books/covers/双城记.webp', '以法国大革命为背景的历史小说，开篇即是文学史上最著名的引言之一', ARRAY['classic','novel','english'], false),
  ('变形记', '变形记', '弗兰兹·卡夫卡', '/books/covers/变形记.webp', '卡夫卡最著名的中篇小说，讲述推销员格里高尔变成甲虫的荒诞故事', ARRAY['classic','novel','philosophy','german'], false),
  ('叶甫盖尼·奥涅金', '叶甫盖尼·奥涅金', '普希金', '/books/covers/叶甫盖尼·奥涅金.webp', '普希金的诗体小说，俄国现实主义文学的奠基之作', ARRAY['classic','poetry','russian'], false),
  ('呼啸山庄', '呼啸山庄', '艾米莉·勃朗特', '/books/covers/呼啸山庄.webp', '英国文学史上最伟大的爱情悲剧之一，讲述希斯克利夫与凯瑟琳的爱恨纠葛', ARRAY['classic','novel','romance','english'], false),
  ('哈克贝利·费恩历险记', '哈克贝利·费恩历险记', '马克·吐温', '/books/covers/哈克贝利·费恩历险记.webp', '马克·吐温的代表作，美国文学的源头之一，讲述少年哈克的密西西比河冒险', ARRAY['classic','novel','adventure','american'], false),
  ('哈姆雷特', '哈姆雷特', '莎士比亚', '/books/covers/哈姆雷特.webp', '莎士比亚四大悲剧之首，丹麦王子复仇的永恒经典', ARRAY['classic','drama','english'], false),
  ('地下室手记', '地下室手记', '陀思妥耶夫斯基', '/books/covers/地下室手记.webp', '陀思妥耶夫斯基的中篇杰作，存在主义文学的先声', ARRAY['classic','novel','philosophy','russian'], false),
  ('城堡', '城堡', '弗兰兹·卡夫卡', '/books/covers/城堡.webp', '卡夫卡的长篇小说，讲述土地测量员K试图进入城堡的荒诞经历', ARRAY['classic','novel','philosophy','german'], false),
  ('基督山伯爵', '基督山伯爵', '大仲马', '/books/covers/基督山伯爵.webp', '大仲马最著名的通俗小说，讲述复仇与宽恕的史诗传奇', ARRAY['classic','novel','adventure','french'], false),
  ('堂吉诃德', '堂吉诃德', '塞万提斯', '/books/covers/堂吉诃德.webp', '西方文学史上第一部现代小说，讲述疯癫骑士的荒诞冒险', ARRAY['classic','novel','adventure','spanish'], false),
  ('复活', '复活', '列夫·托尔斯泰', '/books/covers/复活.webp', '托尔斯泰晚年的长篇小说，讲述贵族聂赫留朵夫的精神觉醒与救赎', ARRAY['classic','novel','philosophy','russian'], false),
  ('外套', '外套', '果戈理', '/books/covers/外套.webp', '果戈理的短篇杰作，圣彼得堡小官吏与一件外套的悲喜故事', ARRAY['classic','short-story','russian'], false),
  ('大卫·科波菲尔', '大卫·科波菲尔', '查尔斯·狄更斯', '/books/covers/大卫·科波菲尔.webp', '狄更斯最具自传色彩的长篇小说，讲述主人公从童年到成年的成长历程', ARRAY['classic','novel','english'], false),
  ('契诃夫短篇小说集', '契诃夫短篇小说集', '契诃夫', '/books/covers/契诃夫短篇小说集.webp', '俄国短篇小说大师契诃夫的经典作品集', ARRAY['classic','short-story','russian'], false),
  ('奥赛罗', '奥赛罗', '莎士比亚', '/books/covers/奥赛罗.webp', '莎士比亚四大悲剧之一，讲述摩尔将军奥赛罗因嫉妒而毁灭的故事', ARRAY['classic','drama','english'], false),
  ('安娜·卡列尼娜', '安娜·卡列尼娜', '列夫·托尔斯泰', '/books/covers/安娜·卡列尼娜.webp', '托尔斯泰的长篇巨著，被誉为最完美的小说，探讨爱情、婚姻与社会', ARRAY['classic','novel','romance','russian'], false),
  ('安徒生童话', '安徒生童话', '安徒生', '/books/covers/安徒生童话.webp', '丹麦童话大师安徒生的经典童话集，包含《丑小鸭》《海的女儿》等名篇', ARRAY['classic','fairy-tale'], false),
  ('审判', '审判', '弗兰兹·卡夫卡', '/books/covers/审判.webp', '卡夫卡的长篇小说，讲述银行职员约瑟夫·K被莫名审判的荒诞故事', ARRAY['classic','novel','philosophy','german'], false),
  ('小王子', '小王子', '安托万·德·圣-埃克苏佩里', '/books/covers/小王子.webp', '世界上最受欢迎的童话之一，用孩子的视角透视成人世界的荒诞', ARRAY['classic','fairy-tale','philosophy','french'], false),
  ('少年维特的烦恼', '少年维特的烦恼', '歌德', '/books/covers/少年维特的烦恼.webp', '歌德的书信体小说，一部感伤主义文学的经典之作', ARRAY['classic','novel','romance','german'], false),
  ('尤利西斯', '尤利西斯', '詹姆斯·乔伊斯', '/books/covers/尤利西斯.webp', '意识流文学的巅峰之作，以一天的时间框架映射整个西方文明', ARRAY['classic','novel','english'], false),
  ('局外人', '局外人', '阿尔贝·加缪', '/books/covers/局外人.webp', '加缪的存在主义代表作，讲述一个对世界冷漠疏离的普通人的故事', ARRAY['classic','novel','philosophy','french'], false),
  ('巴黎圣母院', '巴黎圣母院', '维克多·雨果', '/books/covers/巴黎圣母院.webp', '雨果的长篇小说，以十五世纪巴黎为背景，讲述钟楼怪人卡西莫多的悲剧', ARRAY['classic','novel','french'], false),
  ('强盗', '强盗', '弗里德里希·席勒', '/books/covers/强盗.webp', '席勒的成名戏剧，讲述贵族青年卡尔·摩尔反抗社会的叛逆故事', ARRAY['classic','drama','german'], false),
  ('德伯家的苔丝', '德伯家的苔丝', '托马斯·哈代', '/books/covers/德伯家的苔丝.webp', '哈代最著名的小说，讲述纯洁少女苔丝的悲剧命运', ARRAY['classic','novel','english'], false),
  ('心', '心', '夏目漱石', '/books/covers/心.webp', '夏目漱石的代表作，深入剖析人性中的孤独与利己主义', ARRAY['classic','novel','philosophy','japanese'], false),
  ('快乐王子', '快乐王子', '奥斯卡·王尔德', '/books/covers/快乐王子.webp', '王尔德最著名的童话，讲述快乐王子雕像与小燕子的感人故事', ARRAY['classic','fairy-tale','english'], false),
  ('悉达多', '悉达多', '赫尔曼·黑塞', '/books/covers/悉达多.webp', '黑塞的哲理小说，讲述古印度贵族青年寻求生命真谛的精神之旅', ARRAY['classic','novel','philosophy','german'], false),
  ('悲惨世界', '悲惨世界', '维克多·雨果', '/books/covers/悲惨世界.webp', '雨果的鸿篇巨制，讲述冉·阿让在苦难中寻求救赎的史诗故事', ARRAY['classic','novel','french'], false),
  ('愤怒的葡萄', '愤怒的葡萄', '约翰·斯坦贝克', '/books/covers/愤怒的葡萄.webp', '斯坦贝克的代表作，讲述大萧条时期乔德一家西迁求生的苦难历程', ARRAY['classic','novel','american'], false),
  ('我是猫', '我是猫', '夏目漱石', '/books/covers/我是猫.webp', '夏目漱石的成名作，以猫的视角讽刺明治时代日本社会的种种荒诞', ARRAY['classic','novel','japanese'], false),
  ('战争与和平', '战争与和平', '列夫·托尔斯泰', '/books/covers/战争与和平.webp', '托尔斯泰的史诗巨著，以拿破仑战争为背景描绘俄国社会的全景画卷', ARRAY['classic','novel','russian'], false),
  ('时间机器', '时间机器', '赫伯特·威尔斯', '/books/covers/时间机器.webp', '科幻小说的开山之作，讲述时间旅行者穿越到未来的奇异见闻', ARRAY['classic','novel','english'], false),
  ('月亮与六便士', '月亮与六便士', '毛姆', '/books/covers/月亮与六便士.webp', '毛姆的代表作，以高更为原型讲述一个证券经纪人抛弃一切追求艺术的故事', ARRAY['classic','novel','english'], false),
  ('杀死一只知更鸟', '杀死一只知更鸟', '哈珀·李', '/books/covers/杀死一只知更鸟.webp', '美国现代文学经典，通过孩子的视角探讨种族歧视与正义', ARRAY['classic','novel','american'], false),
  ('李尔王', '李尔王', '莎士比亚', '/books/covers/李尔王.webp', '莎士比亚四大悲剧之一，讲述不列颠国王李尔王因轻信而酿成的家庭悲剧', ARRAY['classic','drama','english'], false),
  ('欧也妮·葛朗台', '欧也妮·葛朗台', '巴尔扎克', '/books/covers/欧也妮·葛朗台.webp', '巴尔扎克《人间喜剧》中的名篇，讲述守财奴葛朗台与女儿的悲剧', ARRAY['classic','novel','french'], false),
  ('死魂灵', '死魂灵', '果戈理', '/books/covers/死魂灵.webp', '果戈理的长篇讽刺小说，讲述乞乞科夫收购死农奴的荒诞故事', ARRAY['classic','novel','russian'], false),
  ('永别了，武器', '永别了，武器', '欧内斯特·海明威', '/books/covers/永别了，武器.webp', '海明威的反战小说，以一战为背景讲述战争中的爱情与幻灭', ARRAY['classic','novel','romance','american'], false),
  ('汤姆·索亚历险记', '汤姆·索亚历险记', '马克·吐温', '/books/covers/汤姆·索亚历险记.webp', '马克·吐温的儿童冒险小说，讲述调皮男孩汤姆的密西西比河畔冒险', ARRAY['classic','novel','adventure','american'], false),
  ('洛丽塔', '洛丽塔', '弗拉基米尔·纳博科夫', '/books/covers/洛丽塔.webp', '纳博科夫最具争议的小说，以华丽的文笔讲述一段禁忌之恋', ARRAY['classic','novel','american'], false),
  ('浮士德', '浮士德', '歌德', '/books/covers/浮士德.webp', '歌德毕生心血之作，讲述学者浮士德与魔鬼梅菲斯特的交易', ARRAY['classic','drama','philosophy','german'], false),
  ('爱玛', '爱玛', '简·奥斯汀', '/books/covers/爱玛.webp', '奥斯汀的成熟之作，讲述自作聪明的爱玛在爱情中成长的故事', ARRAY['classic','novel','romance','english'], false),
  ('玩偶之家', '玩偶之家', '易卜生', '/books/covers/玩偶之家.webp', '易卜生最著名的戏剧，讲述娜拉觉醒并出走的故事，女性主义文学先驱', ARRAY['classic','drama'], false),
  ('理智与情感', '理智与情感', '简·奥斯汀', '/books/covers/理智与情感.webp', '奥斯汀的处女作，讲述达什伍德姐妹截然不同的爱情观', ARRAY['classic','novel','romance','english'], false),
  ('生命中不能承受之轻', '生命中不能承受之轻', '米兰·昆德拉', '/books/covers/生命中不能承受之轻.webp', '昆德拉的代表作，以布拉格之春为背景探讨生命的轻与重', ARRAY['classic','novel','philosophy'], false),
  ('白痴', '白痴', '陀思妥耶夫斯基', '/books/covers/白痴.webp', '陀思妥耶夫斯基的长篇小说，讲述纯真善良的梅什金公爵的悲剧命运', ARRAY['classic','novel','russian'], false),
  ('白鲸', '白鲸', '赫尔曼·梅尔维尔', '/books/covers/白鲸.webp', '美国文学的史诗巨著，讲述亚哈船长追逐白鲸莫比·迪克的执念', ARRAY['classic','novel','adventure','american'], false),
  ('百年孤独', '百年孤独', '加西亚·马尔克斯', '/books/covers/百年孤独.webp', '魔幻现实主义的巅峰之作，讲述布恩迪亚家族七代人的传奇故事', ARRAY['classic','novel','latin-american'], false),
  ('神曲', '神曲', '但丁', '/books/covers/神曲.webp', '中世纪最伟大的文学作品，但丁游历地狱、炼狱和天堂的灵魂之旅', ARRAY['classic','poetry','philosophy','italian'], false),
  ('福尔摩斯探案集', '福尔摩斯探案集', '阿瑟·柯南·道尔', '/books/covers/福尔摩斯探案集.webp', '侦探小说的经典之作，讲述大侦探福尔摩斯与华生的探案故事', ARRAY['classic','short-story','detective','english'], false),
  ('等待戈多', '等待戈多', '塞缪尔·贝克特', '/books/covers/等待戈多.webp', '荒诞派戏剧的代表作，两个人在无尽等待中展开的哲学对话', ARRAY['classic','drama','philosophy'], false),
  ('简·爱', '简·爱', '夏洛蒂·勃朗特', '/books/covers/简·爱.webp', '英国文学经典，讲述孤女简·爱追求自由与尊严的独立女性故事', ARRAY['classic','novel','romance','english'], false),
  ('红与黑', '红与黑', '司汤达', '/books/covers/红与黑.webp', '法国批判现实主义文学的奠基之作，讲述于连的野心与爱情', ARRAY['classic','novel','romance','french'], false),
  ('红字', '红字', '纳撒尼尔·霍桑', '/books/covers/红字.webp', '美国文学的经典，讲述清教徒社会中一个女人佩戴红字A的赎罪故事', ARRAY['classic','novel','american'], false),
  ('红花侠', '红花侠', '奥希兹女男爵', '/books/covers/红花侠.webp', '冒险小说经典，讲述法国大革命时期神秘贵族红花侠的救援行动', ARRAY['classic','novel','adventure','english'], false),
  ('罗密欧与朱丽叶', '罗密欧与朱丽叶', '莎士比亚', '/books/covers/罗密欧与朱丽叶.webp', '莎士比亚最著名的爱情悲剧，两个家族仇人的年轻恋人殉情而死', ARRAY['classic','drama','romance','english'], false),
  ('罪与罚', '罪与罚', '陀思妥耶夫斯基', '/books/covers/罪与罚.webp', '陀思妥耶夫斯基的代表作，讲述穷大学生拉斯柯尔尼科夫的犯罪与救赎', ARRAY['classic','novel','philosophy','russian'], false),
  ('羊脂球', '羊脂球', '莫泊桑', '/books/covers/羊脂球.webp', '莫泊桑的成名短篇，普法战争中一个妓女的高尚与乘客的卑劣形成对比', ARRAY['classic','short-story','french'], false),
  ('美丽新世界', '美丽新世界', '阿道司·赫胥黎', '/books/covers/美丽新世界.webp', '反乌托邦经典三部曲之一，描绘一个以科技控制人类的未来社会', ARRAY['classic','novel','dystopia','english'], false),
  ('群鬼', '群鬼', '易卜生', '/books/covers/群鬼.webp', '易卜生的社会问题剧，揭露维多利亚时代道德伪善的悲剧', ARRAY['classic','drama'], false),
  ('老人与海', '老人与海', '欧内斯特·海明威', '/books/covers/老人与海.webp', '海明威的诺贝尔奖之作，讲述古巴老渔夫与大马林鱼的搏斗', ARRAY['classic','novel','american'], false),
  ('茶花女', '茶花女', '小仲马', '/books/covers/茶花女.webp', '法国文学经典爱情悲剧，讲述巴黎名妓玛格丽特的凄美爱情', ARRAY['classic','novel','romance','french'], false),
  ('荒原狼', '荒原狼', '赫尔曼·黑塞', '/books/covers/荒原狼.webp', '黑塞的代表作，讲述一个知识分子在精神分裂中寻找自我', ARRAY['classic','novel','philosophy','german'], false),
  ('蝇王', '蝇王', '威廉·戈尔丁', '/books/covers/蝇王.webp', '戈尔丁的寓言小说，讲述一群荒岛求生的少年如何退化为野蛮人', ARRAY['classic','novel','english'], false),
  ('远大前程', '远大前程', '查尔斯·狄更斯', '/books/covers/远大前程.webp', '狄更斯的成熟之作，讲述孤儿皮普从卑微到幻灭的成长历程', ARRAY['classic','novel','english'], false),
  ('远离尘嚣', '远离尘嚣', '托马斯·哈代', '/books/covers/远离尘嚣.webp', '哈代的成名作，讲述美丽独立的芭丝谢芭与三个追求者的爱情纠葛', ARRAY['classic','novel','romance','english'], false),
  ('道林·格雷的画像', '道林·格雷的画像', '奥斯卡·王尔德', '/books/covers/道林·格雷的画像.webp', '王尔德唯一的小说，讲述一个美少年的画像替他衰老的寓言故事', ARRAY['classic','novel','philosophy','english'], false),
  ('都柏林人', '都柏林人', '詹姆斯·乔伊斯', '/books/covers/都柏林人.webp', '乔伊斯的短篇小说集，以十五个故事描绘都柏林市民的精神瘫痪', ARRAY['classic','short-story','english'], false),
  ('金阁寺', '金阁寺', '三岛由纪夫', '/books/covers/金阁寺.webp', '三岛由纪夫的代表作，讲述口吃僧人放火烧毁金阁寺的真实事件改编', ARRAY['classic','novel','philosophy','japanese'], false),
  ('银河铁道之夜', '银河铁道之夜', '宫泽贤治', '/books/covers/银河铁道之夜.webp', '宫泽贤治最著名的童话，讲述少年乔万尼在银河列车上的奇幻旅程', ARRAY['classic','fairy-tale','japanese'], false),
  ('阴谋与爱情', '阴谋与爱情', '弗里德里希·席勒', '/books/covers/阴谋与爱情.webp', '席勒的市民悲剧，讲述宰相之子与乐师之女被阴谋摧毁的爱情', ARRAY['classic','drama','romance','german'], false),
  ('隐身人', '隐身人', '赫伯特·威尔斯', '/books/covers/隐身人.webp', '威尔斯的科幻经典，讲述一个科学家发明隐身术后的疯狂与毁灭', ARRAY['classic','novel','english'], false),
  ('雪国', '雪国', '川端康成', '/books/covers/雪国.webp', '川端康成的诺贝尔奖之作，讲述东京男子与雪国艺伎的虚幻爱情', ARRAY['classic','novel','romance','japanese'], false),
  ('雾都孤儿', '雾都孤儿', '查尔斯·狄更斯', '/books/covers/雾都孤儿.webp', '狄更斯的早期代表作，讲述孤儿奥利弗在伦敦的苦难经历', ARRAY['classic','novel','english'], false),
  ('霍乱时期的爱情', '霍乱时期的爱情', '加西亚·马尔克斯', '/books/covers/霍乱时期的爱情.webp', '马尔克斯的爱情史诗，讲述一段跨越半个多世纪的忠贞不渝的爱情', ARRAY['classic','novel','romance','latin-american'], false),
  ('飘', '飘', '玛格丽特·米切尔', '/books/covers/飘.webp', '以美国南北战争为背景的史诗爱情小说，讲述斯嘉丽的坚韧与爱情', ARRAY['classic','novel','romance','american'], false),
  ('高老头', '高老头', '巴尔扎克', '/books/covers/高老头.webp', '巴尔扎克《人间喜剧》的核心作品，讲述父爱的极端与青年的堕落', ARRAY['classic','novel','french'], false),
  ('麦克白', '麦克白', '莎士比亚', '/books/covers/麦克白.webp', '莎士比亚四大悲剧之一，讲述苏格兰将军麦克白因野心而走向毁灭', ARRAY['classic','drama','english'], false),
  ('麦田里的守望者', '麦田里的守望者', 'J.D.塞林格', '/books/covers/麦田里的守望者.webp', '美国青春文学经典，讲述叛逆少年霍尔顿在纽约的两天游荡', ARRAY['classic','novel','american'], false),
  ('鼠疫', '鼠疫', '阿尔贝·加缪', '/books/covers/鼠疫.webp', '加缪的长篇寓言小说，以北非城市爆发鼠疫隐喻人类面对荒诞的态度', ARRAY['classic','novel','philosophy','french'], false)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  author = EXCLUDED.author,
  cover = EXCLUDED.cover,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  featured = EXCLUDED.featured;

INSERT INTO book_chapters (id, book_id, title, cover, status, txt_url, sort_order) VALUES
  ('1', '1984', '1984', '/books/covers/1984.webp', '已完结', '/books/texts/1984/1984.txt', 0),
  ('1', '古典部系列', '冰菓', '/books/covers/古典部系列.webp', '已完结', '/books/texts/古典部系列/古典部系列1.txt', 0),
  ('2', '古典部系列', '愚者的片尾', '/books/covers/古典部系列.webp', '已完结', '/books/texts/古典部系列/古典部系列2.txt', 1),
  ('3', '古典部系列', '库特利亚芙卡的排序', '/books/covers/古典部系列.webp', '已完结', '/books/texts/古典部系列/古典部系列3.txt', 2),
  ('4', '古典部系列', '绕远路的雏偶', '/books/covers/古典部系列.webp', '已完结', '/books/texts/古典部系列/古典部系列4.txt', 3),
  ('5', '古典部系列', '两人距离的概算', '/books/covers/古典部系列.webp', '已完结', '/books/texts/古典部系列/古典部系列5.txt', 4),
  ('6', '古典部系列', '放眼不可理喻的未来', '/books/covers/古典部系列.webp', '已完结', '/books/texts/古典部系列/古典部系列6.txt', 5),
  ('1', '魔女之旅', '第1卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 1.txt', 0),
  ('2', '魔女之旅', '第2卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 2.txt', 1),
  ('3', '魔女之旅', '第3卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 3.txt', 2),
  ('4', '魔女之旅', '第4卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 4.txt', 3),
  ('5', '魔女之旅', '第5卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 5.txt', 4),
  ('6', '魔女之旅', '第6卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 6.txt', 5),
  ('7', '魔女之旅', '第7卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 7.txt', 6),
  ('8', '魔女之旅', '第8卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 8.txt', 7),
  ('9', '魔女之旅', '第9卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 9.txt', 8),
  ('10', '魔女之旅', '第10卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 10.txt', 9),
  ('11', '魔女之旅', '第11卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅 11.txt', 10),
  ('12', '魔女之旅', '第12卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅12.txt', 11),
  ('13', '魔女之旅', '第13卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅13.txt', 12),
  ('14', '魔女之旅', '第14卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅14.txt', 13),
  ('15', '魔女之旅', '第15卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅15.txt', 14),
  ('16', '魔女之旅', '第16卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅16.txt', 15),
  ('17', '魔女之旅', '第17卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅17.txt', 16),
  ('18', '魔女之旅', '第18卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅18.txt', 17),
  ('19', '魔女之旅', '第19卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅19.txt', 18),
  ('20', '魔女之旅', '第20卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅20.txt', 19),
  ('21', '魔女之旅', '第21卷', '/books/covers/魔女之旅.webp', '已完结', '/books/texts/mobitchi/魔女之旅21.txt', 20),
  ('1', '小市民系列', '春季限定草莓塔事件', '/books/covers/小市民系列.webp', '已完结', '/books/texts/小市民系列/春季限定草莓塔事件.txt', 0),
  ('2', '小市民系列', '夏季限定热带水果芭菲事件', '/books/covers/小市民系列.webp', '已完结', '/books/texts/小市民系列/夏季限定热带水果百汇事件.txt', 1),
  ('3', '小市民系列', '秋季限定栗金饨事件(上)', '/books/covers/小市民系列.webp', '已完结', '/books/texts/小市民系列/秋季限定栗金饨事件(上).txt', 2),
  ('4', '小市民系列', '秋季限定栗金饨事件(下)', '/books/covers/小市民系列.webp', '已完结', '/books/texts/小市民系列/秋季限定栗金饨事件(下).txt', 3),
  ('5', '小市民系列', '冬季限定法式巧克力事件', '/books/covers/小市民系列.webp', '已完结', '/books/texts/小市民系列/冬季限定法式巧克力事件.txt', 4),
  ('6', '小市民系列', '巴黎马卡龙之谜', '/books/covers/小市民系列.webp', '已完结', '/books/texts/小市民系列/巴黎马卡龙之谜.txt', 5),
  ('1', '三个火枪手', '三个火枪手', '/books/covers/三个火枪手.webp', '已完结', '/books/texts/三个火枪手/三个火枪手.txt', 0),
  ('1', '了不起的盖茨比', '了不起的盖茨比', '/books/covers/了不起的盖茨比.webp', '已完结', '/books/texts/了不起的盖茨比/了不起的盖茨比.txt', 0),
  ('1', '仲夏夜之梦', '仲夏夜之梦', '/books/covers/仲夏夜之梦.webp', '已完结', '/books/texts/仲夏夜之梦/仲夏夜之梦.txt', 0),
  ('1', '傲慢与偏见', '傲慢与偏见', '/books/covers/傲慢与偏见.webp', '已完结', '/books/texts/傲慢与偏见/傲慢与偏见.txt', 0),
  ('1', '动物农场', '动物农场', '/books/covers/动物农场.webp', '已完结', '/books/texts/动物农场/动物农场.txt', 0),
  ('1', '包法利夫人', '包法利夫人', '/books/covers/包法利夫人.webp', '已完结', '/books/texts/包法利夫人/包法利夫人.txt', 0),
  ('1', '十日谈', '十日谈', '/books/covers/十日谈.webp', '已完结', '/books/texts/十日谈/十日谈.txt', 0),
  ('1', '卡拉马佐夫兄弟', '卡拉马佐夫兄弟', '/books/covers/卡拉马佐夫兄弟.webp', '已完结', '/books/texts/卡拉马佐夫兄弟/卡拉马佐夫兄弟.txt', 0),
  ('1', '双城记', '双城记', '/books/covers/双城记.webp', '已完结', '/books/texts/双城记/双城记.txt', 0),
  ('1', '变形记', '变形记', '/books/covers/变形记.webp', '已完结', '/books/texts/变形记/变形记.txt', 0),
  ('1', '叶甫盖尼·奥涅金', '叶甫盖尼·奥涅金', '/books/covers/叶甫盖尼·奥涅金.webp', '已完结', '/books/texts/叶甫盖尼·奥涅金/叶甫盖尼·奥涅金.txt', 0),
  ('1', '呼啸山庄', '呼啸山庄', '/books/covers/呼啸山庄.webp', '已完结', '/books/texts/呼啸山庄/呼啸山庄.txt', 0),
  ('1', '哈克贝利·费恩历险记', '哈克贝利·费恩历险记', '/books/covers/哈克贝利·费恩历险记.webp', '已完结', '/books/texts/哈克贝利·费恩历险记/哈克贝利·费恩历险记.txt', 0),
  ('1', '哈姆雷特', '哈姆雷特', '/books/covers/哈姆雷特.webp', '已完结', '/books/texts/哈姆雷特/哈姆雷特.txt', 0),
  ('1', '地下室手记', '地下室手记', '/books/covers/地下室手记.webp', '已完结', '/books/texts/地下室手记/地下室手记.txt', 0),
  ('1', '城堡', '城堡', '/books/covers/城堡.webp', '已完结', '/books/texts/城堡/城堡.txt', 0),
  ('1', '基督山伯爵', '基督山伯爵', '/books/covers/基督山伯爵.webp', '已完结', '/books/texts/基督山伯爵/基督山伯爵.txt', 0),
  ('1', '堂吉诃德', '堂吉诃德', '/books/covers/堂吉诃德.webp', '已完结', '/books/texts/堂吉诃德/堂吉诃德.txt', 0),
  ('1', '复活', '复活', '/books/covers/复活.webp', '已完结', '/books/texts/复活/复活.txt', 0),
  ('1', '外套', '外套', '/books/covers/外套.webp', '已完结', '/books/texts/外套/外套.txt', 0),
  ('1', '大卫·科波菲尔', '大卫·科波菲尔', '/books/covers/大卫·科波菲尔.webp', '已完结', '/books/texts/大卫·科波菲尔/大卫·科波菲尔.txt', 0),
  ('1', '契诃夫短篇小说集', '契诃夫短篇小说集', '/books/covers/契诃夫短篇小说集.webp', '已完结', '/books/texts/契诃夫短篇小说集/契诃夫短篇小说集.txt', 0),
  ('1', '奥赛罗', '奥赛罗', '/books/covers/奥赛罗.webp', '已完结', '/books/texts/奥赛罗/奥赛罗.txt', 0),
  ('1', '安娜·卡列尼娜', '安娜·卡列尼娜', '/books/covers/安娜·卡列尼娜.webp', '已完结', '/books/texts/安娜·卡列尼娜/安娜·卡列尼娜.txt', 0),
  ('1', '安徒生童话', '安徒生童话', '/books/covers/安徒生童话.webp', '已完结', '/books/texts/安徒生童话/安徒生童话.txt', 0),
  ('1', '审判', '审判', '/books/covers/审判.webp', '已完结', '/books/texts/审判/审判.txt', 0),
  ('1', '小王子', '小王子', '/books/covers/小王子.webp', '已完结', '/books/texts/小王子/小王子.txt', 0),
  ('1', '少年维特的烦恼', '少年维特的烦恼', '/books/covers/少年维特的烦恼.webp', '已完结', '/books/texts/少年维特的烦恼/少年维特的烦恼.txt', 0),
  ('1', '尤利西斯', '尤利西斯', '/books/covers/尤利西斯.webp', '已完结', '/books/texts/尤利西斯/尤利西斯.txt', 0),
  ('1', '局外人', '局外人', '/books/covers/局外人.webp', '已完结', '/books/texts/局外人/局外人.txt', 0),
  ('1', '巴黎圣母院', '巴黎圣母院', '/books/covers/巴黎圣母院.webp', '已完结', '/books/texts/巴黎圣母院/巴黎圣母院.txt', 0),
  ('1', '强盗', '强盗', '/books/covers/强盗.webp', '已完结', '/books/texts/强盗/强盗.txt', 0),
  ('1', '德伯家的苔丝', '德伯家的苔丝', '/books/covers/德伯家的苔丝.webp', '已完结', '/books/texts/德伯家的苔丝/德伯家的苔丝.txt', 0),
  ('1', '心', '心', '/books/covers/心.webp', '已完结', '/books/texts/心/心.txt', 0),
  ('1', '快乐王子', '快乐王子', '/books/covers/快乐王子.webp', '已完结', '/books/texts/快乐王子/快乐王子.txt', 0),
  ('1', '悉达多', '悉达多', '/books/covers/悉达多.webp', '已完结', '/books/texts/悉达多/悉达多.txt', 0),
  ('1', '悲惨世界', '悲惨世界', '/books/covers/悲惨世界.webp', '已完结', '/books/texts/悲惨世界/悲惨世界.txt', 0),
  ('1', '愤怒的葡萄', '愤怒的葡萄', '/books/covers/愤怒的葡萄.webp', '已完结', '/books/texts/愤怒的葡萄/愤怒的葡萄.txt', 0),
  ('1', '我是猫', '我是猫', '/books/covers/我是猫.webp', '已完结', '/books/texts/我是猫/我是猫.txt', 0),
  ('1', '战争与和平', '战争与和平', '/books/covers/战争与和平.webp', '已完结', '/books/texts/战争与和平/战争与和平.txt', 0),
  ('1', '时间机器', '时间机器', '/books/covers/时间机器.webp', '已完结', '/books/texts/时间机器/时间机器.txt', 0),
  ('1', '月亮与六便士', '月亮与六便士', '/books/covers/月亮与六便士.webp', '已完结', '/books/texts/月亮与六便士/月亮与六便士.txt', 0),
  ('1', '杀死一只知更鸟', '杀死一只知更鸟', '/books/covers/杀死一只知更鸟.webp', '已完结', '/books/texts/杀死一只知更鸟/杀死一只知更鸟.txt', 0),
  ('1', '李尔王', '李尔王', '/books/covers/李尔王.webp', '已完结', '/books/texts/李尔王/李尔王.txt', 0),
  ('1', '欧也妮·葛朗台', '欧也妮·葛朗台', '/books/covers/欧也妮·葛朗台.webp', '已完结', '/books/texts/欧也妮·葛朗台/欧也妮·葛朗台.txt', 0),
  ('1', '死魂灵', '死魂灵', '/books/covers/死魂灵.webp', '已完结', '/books/texts/死魂灵/死魂灵.txt', 0),
  ('1', '永别了，武器', '永别了，武器', '/books/covers/永别了，武器.webp', '已完结', '/books/texts/永别了，武器/永别了，武器.txt', 0),
  ('1', '汤姆·索亚历险记', '汤姆·索亚历险记', '/books/covers/汤姆·索亚历险记.webp', '已完结', '/books/texts/汤姆·索亚历险记/汤姆·索亚历险记.txt', 0),
  ('1', '洛丽塔', '洛丽塔', '/books/covers/洛丽塔.webp', '已完结', '/books/texts/洛丽塔/洛丽塔.txt', 0),
  ('1', '浮士德', '浮士德', '/books/covers/浮士德.webp', '已完结', '/books/texts/浮士德/浮士德.txt', 0),
  ('1', '爱玛', '爱玛', '/books/covers/爱玛.webp', '已完结', '/books/texts/爱玛/爱玛.txt', 0),
  ('1', '玩偶之家', '玩偶之家', '/books/covers/玩偶之家.webp', '已完结', '/books/texts/玩偶之家/玩偶之家.txt', 0),
  ('1', '理智与情感', '理智与情感', '/books/covers/理智与情感.webp', '已完结', '/books/texts/理智与情感/理智与情感.txt', 0),
  ('1', '生命中不能承受之轻', '生命中不能承受之轻', '/books/covers/生命中不能承受之轻.webp', '已完结', '/books/texts/生命中不能承受之轻/生命中不能承受之轻.txt', 0),
  ('1', '白痴', '白痴', '/books/covers/白痴.webp', '已完结', '/books/texts/白痴/白痴.txt', 0),
  ('1', '白鲸', '白鲸', '/books/covers/白鲸.webp', '已完结', '/books/texts/白鲸/白鲸.txt', 0),
  ('1', '百年孤独', '百年孤独', '/books/covers/百年孤独.webp', '已完结', '/books/texts/百年孤独/百年孤独.txt', 0),
  ('1', '神曲', '神曲', '/books/covers/神曲.webp', '已完结', '/books/texts/神曲/神曲.txt', 0),
  ('1', '福尔摩斯探案集', '福尔摩斯探案集', '/books/covers/福尔摩斯探案集.webp', '已完结', '/books/texts/福尔摩斯探案集/福尔摩斯探案集.txt', 0),
  ('1', '等待戈多', '等待戈多', '/books/covers/等待戈多.webp', '已完结', '/books/texts/等待戈多/等待戈多.txt', 0),
  ('1', '简·爱', '简·爱', '/books/covers/简·爱.webp', '已完结', '/books/texts/简·爱/简·爱.txt', 0),
  ('1', '红与黑', '红与黑', '/books/covers/红与黑.webp', '已完结', '/books/texts/红与黑/红与黑.txt', 0),
  ('1', '红字', '红字', '/books/covers/红字.webp', '已完结', '/books/texts/红字/红字.txt', 0),
  ('1', '红花侠', '红花侠', '/books/covers/红花侠.webp', '已完结', '/books/texts/红花侠/红花侠.txt', 0),
  ('1', '罗密欧与朱丽叶', '罗密欧与朱丽叶', '/books/covers/罗密欧与朱丽叶.webp', '已完结', '/books/texts/罗密欧与朱丽叶/罗密欧与朱丽叶.txt', 0),
  ('1', '罪与罚', '罪与罚', '/books/covers/罪与罚.webp', '已完结', '/books/texts/罪与罚/罪与罚.txt', 0),
  ('1', '羊脂球', '羊脂球', '/books/covers/羊脂球.webp', '已完结', '/books/texts/羊脂球/羊脂球.txt', 0),
  ('1', '美丽新世界', '美丽新世界', '/books/covers/美丽新世界.webp', '已完结', '/books/texts/美丽新世界/美丽新世界.txt', 0),
  ('1', '群鬼', '群鬼', '/books/covers/群鬼.webp', '已完结', '/books/texts/群鬼/群鬼.txt', 0),
  ('1', '老人与海', '老人与海', '/books/covers/老人与海.webp', '已完结', '/books/texts/老人与海/老人与海.txt', 0),
  ('1', '茶花女', '茶花女', '/books/covers/茶花女.webp', '已完结', '/books/texts/茶花女/茶花女.txt', 0),
  ('1', '荒原狼', '荒原狼', '/books/covers/荒原狼.webp', '已完结', '/books/texts/荒原狼/荒原狼.txt', 0),
  ('1', '蝇王', '蝇王', '/books/covers/蝇王.webp', '已完结', '/books/texts/蝇王/蝇王.txt', 0),
  ('1', '远大前程', '远大前程', '/books/covers/远大前程.webp', '已完结', '/books/texts/远大前程/远大前程.txt', 0),
  ('1', '远离尘嚣', '远离尘嚣', '/books/covers/远离尘嚣.webp', '已完结', '/books/texts/远离尘嚣/远离尘嚣.txt', 0),
  ('1', '道林·格雷的画像', '道林·格雷的画像', '/books/covers/道林·格雷的画像.webp', '已完结', '/books/texts/道林·格雷的画像/道林·格雷的画像.txt', 0),
  ('1', '都柏林人', '都柏林人', '/books/covers/都柏林人.webp', '已完结', '/books/texts/都柏林人/都柏林人.txt', 0),
  ('1', '金阁寺', '金阁寺', '/books/covers/金阁寺.webp', '已完结', '/books/texts/金阁寺/金阁寺.txt', 0),
  ('1', '银河铁道之夜', '银河铁道之夜', '/books/covers/银河铁道之夜.webp', '已完结', '/books/texts/银河铁道之夜/银河铁道之夜.txt', 0),
  ('1', '阴谋与爱情', '阴谋与爱情', '/books/covers/阴谋与爱情.webp', '已完结', '/books/texts/阴谋与爱情/阴谋与爱情.txt', 0),
  ('1', '隐身人', '隐身人', '/books/covers/隐身人.webp', '已完结', '/books/texts/隐身人/隐身人.txt', 0),
  ('1', '雪国', '雪国', '/books/covers/雪国.webp', '已完结', '/books/texts/雪国/雪国.txt', 0),
  ('1', '雾都孤儿', '雾都孤儿', '/books/covers/雾都孤儿.webp', '已完结', '/books/texts/雾都孤儿/雾都孤儿.txt', 0),
  ('1', '霍乱时期的爱情', '霍乱时期的爱情', '/books/covers/霍乱时期的爱情.webp', '已完结', '/books/texts/霍乱时期的爱情/霍乱时期的爱情.txt', 0),
  ('1', '飘', '飘', '/books/covers/飘.webp', '已完结', '/books/texts/飘/飘.txt', 0),
  ('1', '高老头', '高老头', '/books/covers/高老头.webp', '已完结', '/books/texts/高老头/高老头.txt', 0),
  ('1', '麦克白', '麦克白', '/books/covers/麦克白.webp', '已完结', '/books/texts/麦克白/麦克白.txt', 0),
  ('1', '麦田里的守望者', '麦田里的守望者', '/books/covers/麦田里的守望者.webp', '已完结', '/books/texts/麦田里的守望者/麦田里的守望者.txt', 0),
  ('1', '鼠疫', '鼠疫', '/books/covers/鼠疫.webp', '已完结', '/books/texts/鼠疫/鼠疫.txt', 0)
ON CONFLICT (id, book_id) DO UPDATE SET
  title = EXCLUDED.title,
  cover = EXCLUDED.cover,
  status = EXCLUDED.status,
  txt_url = EXCLUDED.txt_url;

INSERT INTO photos (id, filename, categories) VALUES
  (1, 'photo-001.jpg', ARRAY['landscape','nature']),
  (2, 'photo-002.jpg', ARRAY['landscape','nature']),
  (3, 'photo-003.jpg', ARRAY['landscape','nature']),
  (4, 'photo-004.jpg', ARRAY['landscape','nature']),
  (5, 'photo-005.jpg', ARRAY['landscape','nature']),
  (6, 'photo-006.jpg', ARRAY['landscape','nature']),
  (7, 'photo-007.jpg', ARRAY['landscape','nature']),
  (8, 'photo-008.jpg', ARRAY['landscape','nature']),
  (9, 'photo-009.jpg', ARRAY['landscape','nature']),
  (10, 'photo-010.jpg', ARRAY['landscape','nature']),
  (11, 'photo-011.jpg', ARRAY['landscape','nature']),
  (12, 'photo-012.jpg', ARRAY['landscape','nature']),
  (13, 'photo-013.jpg', ARRAY['landscape','nature']),
  (14, 'photo-014.jpg', ARRAY['landscape','nature']),
  (15, 'photo-015.jpg', ARRAY['landscape','nature']),
  (16, 'photo-016.jpg', ARRAY['landscape','nature']),
  (17, 'photo-017.jpg', ARRAY['landscape','nature']),
  (18, 'photo-018.jpg', ARRAY['landscape','nature']),
  (19, 'photo-019.jpg', ARRAY['landscape','nature']),
  (20, 'photo-020.jpg', ARRAY['landscape','nature']),
  (21, 'photo-021.jpg', ARRAY['landscape','nature']),
  (22, 'photo-022.jpg', ARRAY['landscape','nature']),
  (23, 'photo-023.jpg', ARRAY['landscape','nature']),
  (24, 'photo-024.jpg', ARRAY['landscape','nature']),
  (25, 'photo-025.jpg', ARRAY['landscape','nature']),
  (26, 'photo-026.jpg', ARRAY['landscape','nature']),
  (27, 'photo-027.jpg', ARRAY['landscape','nature']),
  (28, 'photo-028.jpg', ARRAY['landscape','nature']),
  (29, 'photo-029.jpg', ARRAY['landscape','nature']),
  (30, 'photo-030.jpg', ARRAY['landscape','nature']),
  (31, 'photo-031.jpg', ARRAY['landscape','nature']),
  (32, 'photo-032.jpg', ARRAY['landscape','nature']),
  (33, 'photo-033.jpg', ARRAY['landscape','nature']),
  (34, 'photo-034.jpg', ARRAY['landscape','nature']),
  (35, 'photo-035.jpg', ARRAY['landscape','nature']),
  (36, 'photo-036.jpg', ARRAY['landscape','nature']),
  (37, 'photo-037.jpg', ARRAY['landscape','nature']),
  (38, 'photo-038.jpg', ARRAY['landscape','nature']),
  (39, 'photo-039.jpg', ARRAY['landscape','nature']),
  (40, 'photo-040.jpg', ARRAY['landscape','nature']),
  (41, 'photo-041.jpg', ARRAY['landscape','nature']),
  (42, 'photo-042.jpg', ARRAY['landscape','nature']),
  (43, 'photo-043.jpg', ARRAY['landscape','nature']),
  (44, 'photo-044.jpg', ARRAY['landscape','nature']),
  (45, 'photo-045.jpg', ARRAY['landscape','nature']),
  (46, 'photo-046.jpg', ARRAY['landscape','nature']),
  (47, 'photo-047.jpg', ARRAY['landscape','nature']),
  (48, 'photo-048.jpg', ARRAY['landscape','nature']),
  (49, 'photo-049.jpg', ARRAY['landscape','nature']),
  (50, 'photo-050.jpg', ARRAY['landscape','nature']),
  (51, 'photo-051.jpg', ARRAY['landscape','nature']),
  (52, 'photo-052.jpg', ARRAY['landscape','nature']),
  (53, 'photo-053.jpg', ARRAY['landscape','nature']),
  (54, 'photo-054.jpg', ARRAY['landscape','nature']),
  (55, 'photo-055.jpg', ARRAY['landscape','nature']),
  (56, 'photo-056.jpg', ARRAY['landscape','nature']),
  (57, 'photo-057.jpg', ARRAY['landscape','nature']),
  (58, 'photo-058.jpg', ARRAY['landscape','nature']),
  (59, 'photo-059.jpg', ARRAY['landscape','nature']),
  (60, 'photo-060.jpg', ARRAY['landscape','nature']),
  (61, 'photo-061.jpg', ARRAY['landscape','nature']),
  (62, 'photo-062.jpg', ARRAY['landscape','nature']),
  (63, 'photo-063.jpg', ARRAY['landscape','nature']),
  (64, 'photo-064.jpg', ARRAY['landscape','nature']),
  (65, 'photo-065.jpg', ARRAY['landscape','nature']),
  (66, 'photo-066.jpg', ARRAY['landscape','nature']),
  (67, 'photo-067.jpg', ARRAY['landscape','nature']),
  (68, 'photo-068.jpg', ARRAY['landscape','nature']),
  (69, 'photo-069.jpg', ARRAY['landscape','nature']),
  (70, 'photo-070.jpg', ARRAY['landscape','nature']),
  (71, 'photo-071.jpg', ARRAY['landscape','nature']),
  (72, 'photo-072.jpg', ARRAY['landscape','nature']),
  (73, 'photo-073.jpg', ARRAY['landscape','nature']),
  (74, 'photo-074.jpg', ARRAY['landscape','nature']),
  (75, 'photo-075.jpg', ARRAY['landscape','nature']),
  (76, 'photo-076.jpg', ARRAY['landscape','nature']),
  (77, 'photo-077.jpg', ARRAY['landscape','nature']),
  (78, 'photo-078.jpg', ARRAY['landscape','nature']),
  (79, 'photo-079.jpg', ARRAY['landscape','nature']),
  (80, 'photo-080.jpg', ARRAY['landscape','nature']),
  (81, 'photo-081.jpg', ARRAY['landscape','nature']),
  (82, 'photo-082.jpg', ARRAY['landscape','nature']),
  (83, 'photo-083.jpg', ARRAY['landscape','nature']),
  (84, 'photo-084.jpg', ARRAY['landscape','nature']),
  (85, 'photo-085.jpg', ARRAY['landscape','nature']),
  (86, 'photo-086.jpg', ARRAY['landscape','nature']),
  (87, 'photo-087.jpg', ARRAY['landscape','nature']),
  (88, 'photo-088.jpg', ARRAY['landscape','nature']),
  (89, 'photo-089.jpg', ARRAY['landscape','nature']),
  (90, 'photo-090.jpg', ARRAY['landscape','nature']),
  (91, 'photo-091.jpg', ARRAY['landscape','nature']),
  (92, 'photo-092.jpg', ARRAY['landscape','nature']),
  (93, 'photo-093.jpg', ARRAY['landscape','nature']),
  (94, 'photo-094.jpg', ARRAY['landscape','nature']),
  (95, 'photo-095.jpg', ARRAY['landscape','nature']),
  (96, 'photo-096.jpg', ARRAY['landscape','nature']),
  (97, 'photo-097.jpg', ARRAY['landscape','nature']),
  (98, 'photo-098.jpg', ARRAY['landscape','nature']),
  (99, 'photo-099.jpg', ARRAY['landscape','nature']),
  (100, 'photo-100.jpg', ARRAY['landscape','nature']),
  (101, 'photo-101.jpg', ARRAY['landscape','nature']),
  (102, 'photo-102.jpg', ARRAY['landscape','nature']),
  (103, 'photo-103.jpg', ARRAY['landscape','nature']),
  (104, 'photo-104.jpg', ARRAY['landscape','nature']),
  (105, 'photo-105.jpg', ARRAY['landscape','nature']),
  (106, 'photo-106.jpg', ARRAY['landscape','nature']),
  (107, 'photo-107.jpg', ARRAY['landscape','nature']),
  (108, 'photo-108.jpg', ARRAY['landscape','nature']),
  (109, 'photo-109.jpg', ARRAY['landscape','nature']),
  (110, 'photo-110.jpg', ARRAY['landscape','nature']),
  (111, 'photo-111.jpg', ARRAY['landscape','nature']),
  (112, 'photo-112.jpg', ARRAY['landscape','nature']),
  (113, 'photo-113.jpg', ARRAY['landscape','nature']),
  (114, 'photo-114.jpg', ARRAY['landscape','nature']),
  (115, 'photo-115.jpg', ARRAY['landscape','nature']),
  (116, 'photo-116.jpg', ARRAY['landscape','nature']),
  (117, 'photo-117.jpg', ARRAY['landscape','nature']),
  (118, 'photo-118.jpg', ARRAY['landscape','nature']),
  (119, 'photo-119.jpg', ARRAY['landscape','nature']),
  (120, 'photo-120.jpg', ARRAY['landscape','nature']),
  (121, 'photo-121.jpg', ARRAY['landscape','nature']),
  (122, 'photo-122.jpg', ARRAY['landscape','nature']),
  (123, 'photo-123.jpg', ARRAY['landscape','nature']),
  (124, 'photo-124.jpg', ARRAY['landscape','nature']),
  (125, 'photo-125.jpg', ARRAY['landscape','nature'])
ON CONFLICT (id) DO UPDATE SET filename = EXCLUDED.filename;
